### PR TITLE
Upgrade torchtext to 0.3

### PR DESCRIPTION
**Pull request by Victor0118**
Combined with minor bug fixes.

@tuzhucheng Could you review this?

### CODE REVIEW

**Comment by tuzhucheng** [comment]
But v0.3 is not released yet.. https://github.com/pytorch/text/releases

We should stick with stable releases instead of master branch unless we need a particular feature from it.

**Comment by Victor0118** [comment]
I see. That makes sense to me!

**Comment by tuzhucheng** [comment]
However, this branch is useful to keep once v0.3 does become available!

**Comment by Victor0118** [comment]
Yes. I will keep it. Close this PR now.

**Pull request closed without merging**
