### PR TITLE
Fix SM Model Internal Reproducibility Bug

### PR DESCRIPTION
**Pull request by tuzhucheng**
vocab is in different order every time, which means that unknown words are at different positions, causing numpy to have different random states when generating a word vector for the same unknown term in `np.random.uniform(-0.25, 0.25, vec_dim)`.

@gauravbaruah @rosequ please review and verify this fixes the (edited: internal) reproducibility issue.

### CODE REVIEW

**Comment by tuzhucheng** [comment]
I ran the code 2 times using and was able to get the same results.

```
python main.py test1.model --paper-ext-feats
```

```
INFO - -------raw-test MAP 0.758, MRR 0.8211
INFO - -------raw-dev MAP 0.7938, MRR 0.8516
```

**Comment by rosequ** [comment]
@tuzhucheng I get these numbers: raw-test MAP 0.7477, MRR 0.8096
But I didn't delete the cache before training, hoping that we don't have to do it anymore.

**Comment by rosequ** [comment]
I deleted the cache (just in case) and ran it again. The numbers are different from yours but are consistent:
 MAP 0.7477, MRR 0.8096
Did you run your experiments on dragon?

**Comment by tuzhucheng** [comment]
@rosequ yes I ran my experiments on dragon. Maybe this is due to some environment differences.

**Comment by rosequ** [comment]
@tuzhucheng I think so too. In any case, the numbers are consistent, which is greatly relieving. Good job!

**Comment by snapbug** [comment]
Just to jump in -- are they internally consistent (as in you always get the same numbers yourself)? Or externally consistent (you get the same numbers as other people)?

Because the former we've had (at least I have) for some time, it's the latter that's the issue. And the number above aren't externally consistent. If you guys really think it's environmental differences, then docker would put a nail in this coffin by fixing dependencies to specific versions, as has been suggested before in slack.

**Comment by tuzhucheng** [comment]
@snapbug they are internally consistent now, but not externally consistent. They weren't before as shown in the "reproducibility checks" document by Gaurav for me, Royal, and Gaurav.

**Comment by tuzhucheng** [comment]
I think what we can do is define a virtual environment or Conda environment that specifies exactly what version of the packages we are using.

Then, you can create an environment and I'll do the same from this from this environment specifications file (something likes `requirements.txt`). We see if we can get the same metrics from the same machine using two environments, then separate machines.

We can also try Docker which can probably fix environment conditions to a greater extent than just virtualenvs and integrate into frameworks like TravisCI too.

**Comment by rosequ** [comment]
@snapbug they could be externally consistent given the same PyTorch version. @tuzhucheng has the latest version of PyTorch built from source; hence, the numbers are different. Could you report your numbers by training on dragon? The numbers weren't internally consistent earlier. Now, everything including the effective measures and loss remains the same --- even to the last decimal point --- in every epoch, across different training instances.

**Comment by snapbug** [comment]
@tuzhucheng @rosequ Ok, I had thought the numbers were already internally consistent, they had been so on my different runs at least, and there's only one other repeated run in the spreadsheet. I assumed that this issue was all about external consistency.

There's _already_ a `requirements.txt` file in the `sm_cnn` folder, it's possible that it's incomplete? Or that it was overlooked because it's in a subfolder?

**Comment by rosequ** [comment]
@tuzhucheng these are my versions:
python                    3.6.0 
pytorch                   0.1.12
numpy                     1.12.1 
pandas                    0.20.2
gensim                    2.1.0 
nltk                      3.2.2 

Do let me know if you need anything else.

**Comment by snapbug** [comment]
I'll reiterate, there's already a `requirements.txt` file in the `sm_cnn` folder. It contains:

```
gensim==1.0.1
nltk==3.2.1
numpy==1.11.3
pandas==0.19.2
torch==0.1.11+b13b701
```

So if you guys are using different versions to this, it's no wonder that you're getting different results!

My versions match those specified, because I used the tools that were already in the repository to get repeatable results. There's a _small_ argument that it wasn't documented, but it's standard practice for a python project.

**Comment by gauravbaruah** [comment]
I would strongly recommend upgrading the Pytorch version in the requirements file. @rosequ Which version are you using? Since the e2e paper has the working model, we vote that we use the Pytorch version that was used in your e2e experiments.

**Comment by tuzhucheng** [comment]
Let's test individually using exactly the versions in the `requirements.txt` file.

**Comment by tuzhucheng** [comment]
To summarize the discussion so far. This PR has been updated to address getting internally reproducible results only - which means two runs under the same setup should get the same results. It does not address external reproducibility, which will be done in a future PR, and at least most of us agree as suggested by @snapbug earlier Docker is suitable for the task.

**Pull request merged**
