### PR TITLE
Replication of STOA for Reuters Dataset

### PR DESCRIPTION
**Pull request by achyudhk**
- [x] Pack padded sequences in LSTM_baseline

- [x] Add TensorBoardX support for Reuters trainer

- [x] Add Arxiv Academic Paper Dataset (AAPD)

- [ ] SGM for multi-label classification (https://arxiv.org/abs/1806.04822)

- [ ] Regularizing and optimizing LSTM_baseline (https://arxiv.org/abs/1708.02182)

**Work in progress:** Please don't merge until all of the tasks above are done.

### CODE REVIEW

**Comment by achyudhk** [comment]
Corresponding pull-request in Castor-Data: https://git.uwaterloo.ca/jimmylin/Castor-data/merge_requests/11

**Comment by Impavidity** [comment]
@achyudhk Regarding the data format, if you keep label text in dataset, you can use some function for conversion.  I use this scripts format for myself. You could do similar thing:

```
def one_hot_representation(shape, dim, idx, value):
  one_hot = torch.LongTensor(*shape).zero_().to(idx.device)
  one_hot.scatter_(dim, idx, value)
  return one_hot
```

**Comment by achyudhk** [comment]
@Impavidity Thanks, I'll change the existing datasets I pushed to Castor-data to this format.

**Comment by Ashutosh-Adhikari** [comment]
Additional STOAs : 

- [x] [HAN](https://www.cs.cmu.edu/~hovy/papers/16HLT-hierarchical-attention-networks.pdf)
- [ ] [Graph CNN](http://www.cse.ust.hk/~yqsong/papers/2018-WWW-Text-GraphCNN.pdf)

**Comment by Ashutosh-Adhikari** [comment]
Steps for [LSTM_Regularzation](https://arxiv.org/abs/1708.02182) : 
- [x] NT-ASGD (for SGD as an optimizer)
- [ ] Temporal Activation Regularization and Activation Regularization
- [ ] Temporal Averaging for Adam (for Adam as an optimizer)

**Comment by achyudhk** [comment]
@Impavidity I made the changes you requested. Please take a look at the diff.

**Pull request merged**
