### PR TITLE
Idf baseline for QA datasets

### PR DESCRIPTION
**Pull request by rosequ**
- Added a functionality to generate idf scores for TrecQA and WikiQA datasets.

### CODE REVIEW

**Comment by rosequ** [comment]
@HTAustin @gauravbaruah @salman1993 please review...

**Comment by gauravbaruah** [comment]
@rosequ, 
Please make a folder idf_baseline in Castor. 
move your files over to Castor/idf_baseline.
idf-baseline.md then becomes Castor/idf_baseline/README.md
Remove mentions of clean-dev and clean-test from idf-baselines.md; these folders are not created by the files.

**Comment by HTAustin** [comment]
@rosequ 
One quick question about the java. Should we also include java program for this repo? Basically this repo are all python.

**Comment by rosequ** [comment]
@HTAustin @gauravbaruah I have incorporated the changes. Can you have another look and see if we can merge this?

**Comment by gauravbaruah** [comment]
One small change please... 
It would be great if there are pointers on how to generate the index for TrecQA baselines.

**Pull request merged**
