### PR TITLE
change params for sick dataset

### PR DESCRIPTION
**Pull request by likicode**
add more param setting: batch-size, rnn-hidden-dim, lr, optimizer, epochs.

### CODE REVIEW

**Comment by Victor0118** [comment]
And how about the results on MSRVID?
Also, add a table to record your results?

**Comment by tuzhucheng** [comment]
SICK is more challenging that MSRvid, which is actually one of SICK's data sources according to http://alt.qcri.org/semeval2014/cdrom/pdf/SemEval2014001.pdf. I don't think we need to worry about MSRvid anymore (I didn't for my thesis).

**Comment by daemon** [comment]
Look good to me.

**Comment by daemon** [comment]
Please somewhat follow [commit message guidelines](https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53/), e.g., `change params for sick dataset` --> `Change hyperparameters for SICK dataset`

**Pull request merged**
