### PR TITLE
Castor Castor-data Castor-models initial integration

### PR DESCRIPTION
**Pull request by gauravbaruah**
1. sm-model renamed to sm_model
2. relative paths changed to reflect Castor-data in Readme and main.py (see -h)
3. bug fix for SMCastorini.py

Should overlap_features.py be part of Castor-data?

### CODE REVIEW

**Comment by lintool** [comment]
Is someone taking a look at this?

According to [PEP8](https://www.python.org/dev/peps/pep-0008/):

> Function names should be lowercase, with words separated by underscores as necessary to improve readability.
>
> mixedCase is allowed only in contexts where that's already the prevailing style

I assume since we're starting fresh we're using underscores?

**Comment by gauravbaruah** [comment]
What do we want the class names as? lower_case or CamelCase?

**Comment by gauravbaruah** [comment]
updated as per pep8. May need further refinements in the future.

**Comment by salman1993** [comment]
Class names should normally use the CapWords convention. Let's follow the PEP8 convention.
https://www.python.org/dev/peps/pep-0008/#class-names

**Comment by gauravbaruah** [comment]
Closing this, since a new PR for castorini/Castor is coming soon.

**Pull request closed without merging**
